config/routes.rb
Rails.application.routes.draw do

  root "homes#index"
  get "/index", to: "homes#index"
  get "/about", to: "homes#about"

  resources :users do
    resources :reports, only: [:new, :create]
    member do
      get :following, :followers
    end
  end

  resources :places, only: [:index, :show]

  resources  :posts do
    resources :comments, except: [:index]
    resources :reports, only: [:new, :create]
    resources :rates, except: [:index, :show]
  end

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/signin" , to: "sessions#new"
  post "/signin" , to: "sessions#create"

  delete "/log_out", to: "sessions#destroy"
  resources :accounts, only: [:edit]
  resources :relations, only: [:create, :destroy]
  resources :password_resets, except: [:index, :destroy]
  resources :notifications, only: [:index, :destroy]
  resources :searches, only: :index
  mount ActionCable.server, at: "/cable"

  namespace :admin do
    root "dashboards#index"
    get "/index", to: "dashboards#index"
    resources :users
    resources :posts, only: [:index, :show, :destroy]

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/log_out", to: "sessions#destroy"

    resources :posts
    resources :places
    resources :notifications
    resources :reports

    get "/charts", to: "charts#index"
    resources :charts, only: :index
  end
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :posts
  validates :name , presence: true, uniqueness: true
  enum status: [ :active, :archived ]
  scope :newest, ->{order created_at: :desc}
  scope :check_status, ->{where status: :archived}
  scope :search_place, ->(search_place){where("name like '%#{search_place}%'")}
  scope :group_by_type, -> (type) {
    case type
    when type = "week"
      group("DATE_FORMAT(created_at,'%v-%x')").count
    when type = "month"
      group("DATE_FORMAT(created_at,'%b-%x')").count
    when type = "year"
      group("DATE_FORMAT(created_at,'%x')").count
    end
  }
end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < Admin::BaseController
  before_action :load_place, only: [:edit, :update, :destroy]
  def index
    @search_places = Place.search_place(params[:search_place]).newest.paginate page: params[:page], per_page: 8 if params[:search_place]
    @place = Place.new
    @places = Place.paginate page: params[:page], per_page: 8
  end

  def edit;  end

  def create
    @place = Place.new place_params
    if @place.save
      flash[:success] = "Success!"
      redirect_to admin_places_path
    else
      flash[:danger] = "Fails!"
      redirect_to admin_places_path
    end
  end

  def update
    if @place.update place_params
      flash[:success] = "Success!"
      redirect_to admin_places_path
    else
      render :edit
    end
  end

  def destroy
    if @place.status == "active"
      @place.update status: :archived
      flash[:success] = "Success!"
      redirect_to admin_places_path
    else
      @place.update status: :active
      flash[:success] = "Success!"
      redirect_to admin_places_path
    end
  end

  private
  def load_place
    @place = Place.find_by id: params[:id]
  end

  def place_params
    params.require(:place).permit :name, :status, :image
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = Place.paginate page: params[:page], per_page: 5
  end
  def show
    @place = Place.find_by id: params[:id]
    places_max_posts
    @posts = @place.posts.newest.paginate page: params[:page], per_page: 5
  end

  private
  def place_params
    params.require(:place).permit :name
  end
end

app/views/admin/places/_new.html.erb
<div class="modal" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">New Place</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <%= form_for [:admin, place] do |f| %>
          <%= render "admin/shared/error_place_messages"%>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, placeholder: "Name..." , class: "form_control" %>
          </div>
          <br>
          <div class="form-group">
            <%= f.hidden_field :status, value: :archived %>
            <%= f.submit "Create", class: "btn btn-primary" %>
          </div>
          <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/admin/places/_place.html.erb
<tr>
  <td><%= place.id %></td>
  <td><%= place.name%></td>
  <td></td>
  <td><%= image_tag "lt-03", class: "img-fluid-1" %></td>
  <td>
    <%= link_to "Edit", edit_admin_place_path(place), class: "btn btn-warning" %>
    <% if place.status == "archived" %>
      <%= link_to "Remove", admin_place_path(place), method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= link_to "Restore", admin_place_path(place), method: :delete, class: "btn btn-secondary" %>
    <% end %>
  </td>
</tr>

app/views/admin/places/edit.html.erb
<section class="articles-area section-padding-0-100">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-8">
        <div class="mt-100">
          <div class="login-panel panel panel-default">
            <h1><div class="panel-heading">Update Place</div></h1>
            <div class="panel-body">
              <%= form_for [:admin, @place] do |f| %>
                <%= render "admin/shared/error_place_messages"%>
                <div class="form-group">
                  <%= f.label :name %>
                  <%= f.text_field :name, placeholder: @place.name , class: "form_control" %>
                </div>
                <div class="form-group">
                  <%= f.submit "Update", class: "btn btn-primary" %>
                </div>
              <% end %>
              <%= link_to "Quay lai", admin_places_path, class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/places/index.html.erb
<div class="container">
  <h1>Place Managerment</h1>
  <div class="input-group">
    <%= form_tag admin_places_path, method: :get do %>
      <%= text_field_tag :search_place, params[:search_place], class: "form-control", placeholder: "Search for place...", aria: {label: "Search", describedby: "basic-addon2"}%>
      <div class="input-group-append">
        <%= submit_tag "Search", class: "btn btn-primary btn-sm"  %>
      </div>
    <% end %>
  </div>
  <td><%= link_to "+ New", "#", data: {toggle: "modal", target: "#myModal"}, class: "btn btn-primary btn-sm" %></td>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Count Post</th>
        <th>Image</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= will_paginate @places %>
      <% if params[:search_place] %>
        <%= render @search_places %>
      <% else %>
        <%= render @places %>
      <% end %>
    </tbody>
  </table>
</div>
<%= render "admin/places/new", place: @place %>