config/routes.rb
Rails.application.routes.draw do

  root "homes#index"
  get "/index", to: "homes#index"
  get "/about", to: "homes#about"

  resources :users do
    resources :reports, only: [:new, :create]
    member do
      get :following, :followers
    end
  end

  resources :places, only: [:index, :show]

  resources  :posts do
    resources :comments, except: [:index]
    resources :reports, only: [:new, :create]
    resources :rates, except: [:index, :show]
  end

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/signin" , to: "sessions#new"
  post "/signin" , to: "sessions#create"

  delete "/log_out", to: "sessions#destroy"
  resources :accounts, only: [:edit]
  resources :relations, only: [:create, :destroy]
  resources :password_resets, except: [:index, :destroy]
  resources :notifications, only: [:index, :destroy]
  resources :searches, only: :index
  mount ActionCable.server, at: "/cable"

  namespace :admin do
    root "dashboards#index"
    get "/index", to: "dashboards#index"
    resources :users
    resources :posts, only: [:index, :show, :destroy]

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/log_out", to: "sessions#destroy"

    resources :posts
    resources :places
    resources :notifications
    resources :reports

    get "/charts", to: "charts#index"
    resources :charts, only: :index
  end
end

app/views/layouts/admin/_footer.html.erb
<footer class="sticky-footer">
 <div class="container my-auto">
   <div class="copyright text-center my-auto">
     <span> © 2019 SUN* Journey . All Rights Reserved</span>
   </div>
 </div>
</footer>
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>
<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1"
  role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Do You Want Log Out ?</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <%= button_to "Logout", admin_log_out_path, method: :delete, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">
  <%= link_to "Admin", admin_root_path, class: "navbar-brand mr-1" %>
  <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
    <i class="fas fa-bars"></i>
  </button>
  <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
  </form>
  <ul class="navbar-nav ml-auto ml-md-0">
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell fa-fw"></i>
        <span class="badge badge-danger" id="noti_counter"><%= @new_notifications_count.size %></span>
      </a>
      <%= render "admin/notifications/notification_dropdown" %>
    </li>
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-envelope fa-fw"></i>
        <span class="badge badge-danger"><%= @reports_count.size %></span>
      </a>
      <%= render "admin/reports/report_dropdown" %>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user-circle fa-fw"></i>
      </a>
        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <li><%= link_to "#{current_admin.name}", admin_user_path(current_admin), class: "dropdown-item" %></li>
          <li><%= link_to "Back HomePage", root_path, class:
            "dropdown-item" %></li>
          <li class="divider"></li>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">Log Out</a>
        </ul>
    </li>
  </ul>
</nav>

app/views/layouts/admin/_sidebar.html.erb
<ul class="sidebar navbar-nav">
  <li class="nav-item active">
    <%= link_to admin_root_url, class: "nav-link" do %>
      <i class="fas fa-fw fa-tachometer-alt"></i>
      Dashboard
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to admin_charts_path, class: "nav-link" do %>
    <i class="fas fa-fw fa-chart-area"></i>
    Chart
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to  admin_posts_path, class: "nav-link" do %>
    <i class="fas fa-fw fa-table"></i>
    Post Managerment
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to  admin_places_path, class: "nav-link" do %>
    <i class="fa fa-map-marker" aria-hidden="true"></i>
    Place Managerment
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to admin_users_path, class: "nav-link" do %>
      <i class="fa fa-users" aria-hidden="true"></i>
      Users
    <% end  %>
  </li>
</ul>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pr1805Journey</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "admin/application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "admin/application",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  </head>
  <body>
    <% if controller.controller_name == "sessions" %>
       <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
    <% else %>
      <%= render "layouts/admin/header" %>
        <div id="wrapper">
          <%= render "layouts/admin/sidebar" %>
          <div class="container">
             <% flash.each do |message_type, message| %>
               <div class="alert alert-<%= message_type %>"><%= message %></div>
             <% end %>
             <%= yield %>
          </div>
        </div>
        <%= render "layouts/admin/footer" %>
    <% end %>
  </body>
</html>