config/routes.rb
Rails.application.routes.draw do

  root "homes#index"
  get "/index", to: "homes#index"
  get "/about", to: "homes#about"

  resources :users do
    resources :reports, only: [:new, :create]
    member do
      get :following, :followers
    end
  end

  resources :places, only: [:index, :show]

  resources  :posts do
    resources :comments, except: [:index]
    resources :reports, only: [:new, :create]
    resources :rates, except: [:index, :show]
  end

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/signin" , to: "sessions#new"
  post "/signin" , to: "sessions#create"

  delete "/log_out", to: "sessions#destroy"
  resources :accounts, only: [:edit]
  resources :relations, only: [:create, :destroy]
  resources :password_resets, except: [:index, :destroy]
  resources :notifications, only: [:index, :destroy]
  resources :searches, only: :index
  mount ActionCable.server, at: "/cable"

  namespace :admin do
    root "dashboards#index"
    get "/index", to: "dashboards#index"
    resources :users
    resources :posts, only: [:index, :show, :destroy]

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/log_out", to: "sessions#destroy"

    resources :posts
    resources :places
    resources :notifications
    resources :reports

    get "/charts", to: "charts#index"
    resources :charts, only: :index
  end
end

app/models/report.rb
class Report < ApplicationRecord
  scope :newest , -> {order  created_at: :desc}
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::BaseController
  before_action :load_report, only: :show
  def index;  end

  def show;  end

  private
  def load_report
    @report = Report.find_by id: params[:id]
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :load_post, only: [:new, :create]

  def new
    @report = Report.new
  end

  def create
    if logged_in?
      @report = Report.new report_params
      if @report.save
        Notification.create(send_from_id: current_user.id, send_to_id: @report.send_to_id,
          send_from_type: "Reported", send_to_type: @report.send_to_type,
          report_id: @report.id, post_id: @report.url, comment_id: "")
        flash[:success] = "Success!"
        respond_to do |format|
          format.html{redirect_to root_path}
          format.js
        end
      else
        flash[:warning] = "Fails!"
        render :new
      end
    else
      flash[:warning] = "Not Auth"
      redirect_to sign_in_path
    end
  end

  private

  def report_params
    params.require(:report).permit :content, :send_to_id, :send_to_type, :url
  end

  def load_post
    @post = Post.find_by id: params[:post_id]
  end
end

app/views/admin/reports/_content.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h4 class="modal-title">Modal Heading</h4>
      <button type="button" class="close btn-close-modal" data-dismiss="modal">&times;</button>
    </div>
    <div class="modal-body">
      <textarea>
      <%= report.content %>
    </textarea>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-danger btn-close-modal" data-dismiss="modal">Close</button>
    </div>
  </div>
</div>

app/views/admin/reports/_report_dropdown.html.erb
<div class="dropdown-menu dropdown-menu-right" aria-labelledby="messagesDropdown">
  <% @reports_limits.each do |report| %>
    <%= render "admin/notifications/notification", notification: report %>
  <% end %>
  <div class="dropdown-divider"></div>
  <%= link_to "See All", admin_reports_path, class: "dropdown-item" %>
</div>

app/views/admin/reports/index.html.erb
<div class="container">
  <h1>Reports Managerment</h1>
  <% @reports.each do |report| %>
    <%= render "admin/notifications/notification", notification: report %>
    <%= link_to "Remove", admin_notification_path(report) , method: :delete,
      data: {confirm: "Are you sure ?"} %>
    <%= link_to "Details", admin_report_path(report.report_id), remote: true,
      data: {target: "#myModal", toggle: "modal"}%>
  <% end %>
  <div class="modal fade" id="myModal" role="dialog">
  </div>
</div>

app/views/admin/reports/show.js.erb
$('#myModal').html("<%=  j(render('admin/reports/content', report: @report)) %>");
$('#myModal').modal('show');