config/routes.rb
Rails.application.routes.draw do

  root "homes#index"
  get "/index", to: "homes#index"
  get "/about", to: "homes#about"

  resources :users do
    resources :reports, only: [:new, :create]
    member do
      get :following, :followers
    end
  end

  resources :places, only: [:index, :show]

  resources  :posts do
    resources :comments, except: [:index]
    resources :reports, only: [:new, :create]
    resources :rates, except: [:index, :show]
  end

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/signin" , to: "sessions#new"
  post "/signin" , to: "sessions#create"

  delete "/log_out", to: "sessions#destroy"
  resources :accounts, only: [:edit]
  resources :relations, only: [:create, :destroy]
  resources :password_resets, except: [:index, :destroy]
  resources :notifications, only: [:index, :destroy]
  resources :searches, only: :index
  mount ActionCable.server, at: "/cable"

  namespace :admin do
    root "dashboards#index"
    get "/index", to: "dashboards#index"
    resources :users
    resources :posts, only: [:index, :show, :destroy]

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/log_out", to: "sessions#destroy"

    resources :posts
    resources :places
    resources :notifications
    resources :reports

    get "/charts", to: "charts#index"
    resources :charts, only: :index
  end
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::BaseController

  def index
    type = params[:type] || "month"
    @users = User.group_by_type type
    @posts = Post.group_by_type type
    @places = Place.group_by_type type
  end
end

app/views/admin/dashboards/index.html.erb
<div id="content-wrapper">
  <div class="container-fluid">
    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <%= link_to "Dashboard", admin_root_url %>
      </li>
      <li class="breadcrumb-item active">Overview</li>
    </ol>
    <!-- Icon Cards-->
    <div class="row">
      <div class="col-xl-3 col-sm-6 mb-3">
        <div class="card text-white bg-primary o-hidden h-100">
          <div class="card-body">
            <div class="card-body-icon">
              <i class="fas fa-fw fa-comments"></i>
            </div>
            <div class="mr-5"><%= User.all.size %> Users</div>
          </div>
          <%= link_to admin_users_path, class: "card-footer text-white clearfix small z-1" do  %>
            <span class="float-left">View Details</span>
            <span class="float-right">
              <i class="fas fa-angle-right"></i>
            </span>
          <% end %>
        </div>
      </div>
      <div class="col-xl-3 col-sm-6 mb-3">
        <div class="card text-white bg-warning o-hidden h-100">
          <div class="card-body">
            <div class="card-body-icon">
              <i class="fas fa-fw fa-list"></i>
            </div>
            <div class="mr-5"><%= Post.all.size %> Posts</div>
          </div>
          <%= link_to admin_posts_path, class: "card-footer text-white clearfix small z-1" do %>
            <span class="float-left">View Details</span>
            <span class="float-right">
              <i class="fas fa-angle-right"></i>
            </span>
          <% end %>
        </div>
      </div>
      <div class="col-xl-3 col-sm-6 mb-3">
        <div class="card text-white bg-success o-hidden h-100">
          <div class="card-body">
            <div class="card-body-icon">
              <i class="fas fa-fw fa-shopping-cart"></i>
            </div>
            <div class="mr-5"><%= Place.all.size %> Places</div>
          </div>
          <%= link_to admin_places_path, class: "card-footer text-white clearfix small z-1" do %>
            <span class="float-left">View Details</span>
            <span class="float-right">
              <i class="fas fa-angle-right"></i>
            </span>
          <% end %>
        </div>
      </div>
      <div class="col-xl-3 col-sm-6 mb-3">
        <div class="card text-white bg-danger o-hidden h-100">
          <div class="card-body">
            <div class="card-body-icon">
              <i class="fas fa-fw fa-life-ring"></i>
            </div>
            <div class="mr-5"><%= @new_notifications_count.size %> Notifications New!</div>
          </div>
          <%= link_to admin_notifications_path, class: "card-footer text-white clearfix small z-1" do %>
            <span class="float-left">View Details</span>
            <span class="float-right">
              <i class="fas fa-angle-right"></i>
            </span>
          <% end %>
        </div>
      </div>
    </div>

    <!-- Area Chart Example-->
  <%= render "admin/charts/abc" %>
  </div>
</div>